### ISSUE TITLE
Some errors in the codes

### ISSUE THREAD

**Issue by drdh** [Khrylx/Transform2Act#1]
1. There is no `create_dirs` argument in `Config` class's init function.  https://github.com/Khrylx/Transform2Act/blob/9c490374947407f4680559a1cf77520df28f8af2/design_opt/train.py#L22 

2. When `num_threads >= 2`, the code gets stuck in the following line https://github.com/Khrylx/Transform2Act/blob/9c490374947407f4680559a1cf77520df28f8af2/design_opt/models/jsmlp.py#L24 `multiprocessing` might be the reason. When `num_threads=1` and `Queue` was not use, everything goes fine. I setup a conda environment as the instructions in README. Have you ever encountered this bug?

**Comment by Khrylx** [comment]
Hello,

Thanks for spotting the error with config!
For multiprocessing, you can try to set the following environment variable to avoid problems with multiprocess sampling:    
```
export OMP_NUM_THREADS=1
```

**Comment by drdh** [comment]
Thanks, it solves my problem.
